name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install MPI
      run: |
        sudo apt-get update && sudo apt-get install -y libopenmpi-dev

    - name: Install cmake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure Cmake
      run: cmake -S . -B build
      

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: ctest --test-dir build

    - name: Install Singularity dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            autoconf \
            automake \
            cryptsetup \
            fuse2fs \
            fuse \
            git \
            libfuse-dev \
            libglib2.0-dev \
            libseccomp-dev \
            libtool \
            pkg-config \
            runc \
            squashfs-tools \
            squashfs-tools-ng \
            uidmap \
            wget \
            zlib1g-dev \

    - name: Install Singularity
      run: |
        wget https://github.com/sylabs/singularity/releases/download/v4.1.3/singularity-ce_4.1.3-jammy_amd64.deb
        sudo dpkg -i singularity-ce_4.1.3-jammy_amd64.deb
      
    - name: Build Singularity container
      run: |
        sudo singularity build matr.sif Singularity.def

    - name: Install sshpass
      run: sudo apt-get update && sudo apt-get install -y sshpass

    - name: Transfer stuff via SPC
      run: |
        sshpass -p "${{ secrets.PASSWORD }}" scp -o StrictHostKeyChecking=no matr.sif matrixA.txt matrixB.txt job.sh a08trb70@login.g100.cineca.it:～

    - name: Run job via SSH
      run: |
        ssh-keygen -f "/home/runner/.ssh/known_hosts" -R "login.g100.cineca.it"
        sshpass -p "${{ secrets.PASSWORD }} ssh -o StrictHostKeyChecking=no a08trb70@login.g100.cineca.it "sbatch job.sh"

