name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MPI
      run: |
        sudo apt-get update && sudo apt-get install -y mpich

    - name: Install cmake
      run: sudo apt-get install -y cmake

    - name: Compile matrix multiplication
      run: mpicc -o matrix_multiplication matrix_multiplication.c

    - name: Run tests
      run: |
        mpirun -np 2 ./matrix_multiplication matrixA.txt matrixB.txt

    - name: Build Singularity container
      run: |
        sudo apt-get update && sudo apt-get install -y singularity-container
        singularity build matrix_multiplication.sif Singularity.def

